credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$Jz1Lv6eM9siZ0olCBjl7Pe.Gp12Ohntl1ziocgBJ7wg8ihYIOmsJ. # To be replaced with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$vziD//yznsdoriyPhqTLWOZdPRzq5SrNFYdU1YJLeRWZPj3Fef8s6 # To be replaced with hashed password
cookie:
  expiry_days: 0
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
